### ISSUE TITLE
iframe sample is not working on when presentation is served via https

### ISSUE THREAD

**Issue by GregOnNet** [Angular2Buch/presentations#1]
@JohannesHoppe  Kannst da noch mal schauen?

![image](https://cloud.githubusercontent.com/assets/444278/10506359/72115e98-7317-11e5-9c31-74489fcc187c.png)

**Comment by GregOnNet** [comment]
Ach und. GEILER SCHEISS mit dem `iframe`.
Klasse Idee

**Comment by GregOnNet** [comment]
Lokal funktioniert es :+1:

**Comment by JohannesHoppe** [comment]
Bin im Zug ohne WLAN. `.../book-rating-app/index.html` sollte klappen!

Von meinem Windows Phone gesendet

**Comment by GregOnNet** [comment]
Habs in 0481afd500c6d3d62b51305ceca7591d9f44980f umgesetzt.
... Warte auf gh-pages. :watch:

**Comment by GregOnNet** [comment]
Funktionier: https://angular2buch.de/presentations/book-rating/#/10

**Comment by JohannesHoppe** [comment]
BDD - Bahn Driven Development :sunglasses:
