### ISSUE TITLE
Beispiel App in den Slides ist wieder kapuut

### ISSUE THREAD

**Issue by GregOnNet** [Angular2Buch/presentations#2]
Der iFrame zeigt nichts an.
In der Console kommt aber auch kein Fehler.

https://angular2buch.de/presentations/book-rating/#/11

![image](https://cloud.githubusercontent.com/assets/444278/10521556/c44eb33c-7370-11e5-89fb-5207eda6848a.png)

**Comment by JohannesHoppe** [comment]
Upsi! :-)
